spring:
  rabbitmq:
    listener:
      type: stream
      stream:
        native-listener: true
    host: rabbitmq
    port: 5672
    stream:
      host: rabbitmq
      port: 5552

  cloud:
    function:
      definition: testConsumer
    stream:
      rabbit:
        bindings:
          testConsumer-in-0:
            consumer:
              containerType: stream
      bindings:
        testConsumer-in-0:
          destination: test
          group: demo
        testProducer-out-0:
          destination: test
