spring:
  rabbitmq:
    listener:
      type: stream
      stream:
        native-listener: true
        offset: first
    host: rabbitmq
    port: 5672
    stream:
      host: rabbitmq
      port: 5552

  cloud:
    function:
      definition: testConsumer
    stream:
      rabbit:
        bindings:
          testConsumer-in-0:
            offset: first
            consumer:
              containerType: stream
              offset: first
              stream:
                offset: first
      bindings:
        testConsumer-in-0:
          group: demo
          destination: test
          offsetType: first
        testSupplier-out-0:
          destination: test
